### ISSUE TITLE
Implement a parameter to disable user registration

### ISSUE THREAD

**Issue by PascalTemel** [WeebDev/loli-safe#12]
I'm not sure if this is useful for anybody else, but I only want to allow certain users to be able to upload files. To achieve this currently, I hid the registration button from the auth form, which is certainly not a proper way to do it.

Please evaluate if this is something you'd like to have in the project or if I should hack it into my implementation myself.

**Comment by iCrawl** [comment]
Well, considering "private" mode being an invite only upload service, you would expect some sort of sign up. Wether it be through a registration form or some sort of "email me to get access".

But you are correct, it doesn't seem right to me, setting it to private and just being able to sign up to use the upload service. I think the private setting needs to prevent people from uploading until verified.

**Comment by Pitu** [comment]
User registration can already be disabled by setting `enableUserAccounts: false` on the config file. I understand there still needs to be something else there to request for an invite or even an admin being able to create a new user account, but for the time being by toggling that setting you should be good.

**Comment by iCrawl** [comment]
You misunderstand. By setting it to private, it would be nice to still allow registering users, but if private is checked, make the user accounts require a verification (this can be done by the admin), before they can upload stuff.
As it is right now, you can just sign up and upload freely even if its on private mode.

**Comment by iCrawl** [comment]
Because as of right now it feels like the "private" setting is more of a `"allowAnonUploads": false`

**Comment by Pitu** [comment]
Oh I understand perfectly, that's why I said it still needs some work.

But regarding his first comment saying he is hiding the register button in the form, you can avoid doing that by simply toggling the corresponding setting on the config file.
>I hid the registration button from the auth form, which is certainly not a proper way to do it.

**Comment by iCrawl** [comment]
Oh good. I just wanted to make sure theres no misunderstanding 👍

**Comment by PascalTemel** [comment]
To make my use-case clearer: I want several people, for whom I have created accounts, to be able to upload files and manage them through their dashboard. I dont want unregistered users to be able to upload anything.

**Comment by iCrawl** [comment]
Oh yea, if you create accounts for them you can just disallow registering accounts, and make it private in the settings.
The button will still be there, but it wont work, try it out 😉

**Comment by PascalTemel** [comment]
Thanks for the tip both of you, Ill try that.
