### ISSUE TITLE
Generate thumbnails on file upload instead of first list view

### ISSUE THREAD

**Issue by PascalTemel** [WeebDev/loli-safe#14]
Currently, the thumbnails are generated when a user opens the associated album (or user uploads if no album is specified). This results in broken images for the thumbnails the first time the user views the list.

I propse that the thumbnails should be generated on upload.

Sorry about the issue spam btw.

**Comment by Pitu** [comment]
I'll take a look at this this week

**Comment by Pitu** [comment]
My weeks are 25 days long. This is already solved in the latest release
