### ISSUE TITLE
pomf-spec

### ISSUE THREAD

**Issue by alucard0134** [WeebDev/loli-safe#3]

**Comment by alucard0134** [comment]
afaik this doesn't really follow any the pomf API specification to become an alternative. chances our if you implement the spec i'll probably migrate cuntflaps to this

**Comment by iCrawl** [comment]
Whats missing for the pomf-standard, an array of files?
Implementing CSV seems like a waste.

**Comment by alucard0134** [comment]
read it, and if you wanna know why csv is needed i dare you to go into #pomfret and say that

**Comment by Pitu** [comment]
nah
