### ISSUE TITLE
Chrome extension dashboard url for safe.moe

### ISSUE THREAD

**Issue by riesza** [WeebDev/loli-safe#38]
![wpygd 1](https://cloud.githubusercontent.com/assets/1399263/25578993/04f05d4a-2e74-11e7-99f4-a50da5c6c5ad.png)
Clicking this directs you to https://safe.moe/dashboard when the correct url would probably be https://safe.moe/panel

**Comment by iCrawl** [comment]
Should be posted here:

https://github.com/WeebDev/loli-safe-extension

But yes, this is because safe.moe uses panel instead of dashboard (which is the original name).
