### ISSUE TITLE
Client-side compression to speedup upload

### ISSUE THREAD

**Issue by gailingmic** [WeebDev/loli-safe#4]
Hello Weeb,

im thinking of adding clientside compression to speedup the upload.
The only bad thing is it doesnt really have any benefits for JPG, PNG, zip (obv.) as they are already compressed quite good. Where it really shines it with Text documents, some binary formats and RAW images.

would you like me to add it and make a PR?

Greetings from Germoney,
Michell

**Comment by alucard0134** [comment]
Of course you can make a PR, I personally have a separate nginx server for cuntflaps which does compression for me, but we can use this for the actual project

**Comment by gailingmic** [comment]
you have a nginx that does download compression. but it doesnt compress the real slow part, the uploading of files ;-)

**Comment by iCrawl** [comment]
This seems like a much needed feature.
How would you intend going for that? gzipping files before uploading?

**Comment by alucard0134** [comment]
oh shit waddup PR THAT SHIT

**Comment by gailingmic** [comment]
yes gzipping before uploading in the browser, maybe even add webworkers to split large files up in chunks, and then uploading them.

i will add a PR when im home

**Comment by iCrawl** [comment]
We would gladly appreciate a PR with gzipping functionality 👍

**Comment by alucard0134** [comment]
![me when good shit arises](https://a.cuntflaps.me/Jf2tu.png)

**Comment by gailingmic** [comment]
hadnt had time yesterday will do later today

**Comment by Pitu** [comment]
@gailingmic have you had the time to look into this feature by any chance?

**Comment by gailingmic** [comment]
yes i got it working in my local instance will push it later today

**Comment by alucard0134** [comment]
okie dad

**Comment by Pitu** [comment]
Closed since it hasn't had any development in over 2 months
