### ISSUE TITLE
Add ratelimit

### ISSUE THREAD

**Issue by Pitu** [WeebDev/loli-safe#5]
It's necessary to add rate limiting on login and register endpoints

**Comment by iCrawl** [comment]
How needed is this tho? What benefit would that have?

**Comment by gailingmic** [comment]
the benefit would obviously be that ratelimiting protects against bruteforce.

i used [express-rate-limit](https://github.com/nfriedly/express-rate-limit) before and it works really well

**Comment by iCrawl** [comment]
Oh I'm sure it does, but since this is a public endpoint.
It just sounded more like he wants to ratelimit it with something that isnt 3/5s or something. Thats why I got curious as to how it's important.
3/5s is a standard thing where I come from on public endpoints atleast.

**Comment by gailingmic** [comment]
i would say its better to ratelimit single users after they had x amount of requests in 1 minute for the next couple minutes

**Comment by iCrawl** [comment]
I guess this decision more or less depends on the userbase you aim for.
I totally agree that bruteforcing and abuse is one of the things you have to deal with as a public service, but on the other hand how important is it as a file-hoster. If someone decides to register with 3 accounts, they are totally free to do that, but theres no real benefit to it since we dont limit peoples upload "amount" per account.

**Comment by gailingmic** [comment]
nonono you understand rate-limiting wrong it just limits the user (mostly by IP or cookie) of registering more than <amount> of users in <amount of time>. they are still allowed to have as many accounts as they want but they cant create them using a script in 1 second

**Comment by iCrawl** [comment]
You might get that picture from how I described it, sorry.
I totally understand ratelimiting, it's just that I don't see the point in limiting them more than 3/5s or 1/5s.
Lets say the use a script to do that, even with a limit of 1/5s it would still take them a while to get a lot of accounts for... no purpose?

**Comment by gailingmic** [comment]
yea i missunderstood you 😿 theres no point of having 1337x accounts yes but people will do it just to annoy you :^) i would say its the best to add that feature and making it configurable in the config

**Comment by iCrawl** [comment]
I agree with you on this 👍

**Comment by alucard0134** [comment]
yeah people will try spamming the panel to ramp up CPU, this happened on the old panel before for cuntflaps

**Comment by Pitu** [comment]
The register limit would prevent people from running a script creating infinite accounts, which is just a performance issue. The login endpoint on the other hand, is important. For the time being as there are no admin roles the only admin is the root account, which already knowing the username makes it easy to set up a script to try and brute force your way in.

**Comment by Pitu** [comment]
Implemented
